### PR TITLE
Add LabelMap tests

### PR DESCRIPTION
**Pull request by creichert**
This should help. However, I think the test is failing so we will see what the CI says.

### CODE REVIEW

**Comment by creichert** [comment]
```
LabelMap
  LabelMap
Static (fromList [("com",Unassigned (Static (fromList [("someapp",Unassigned (Static (fromList [("api",Assigned _ (Static (fromList [("bla",Assigned _ (EmptyLabelMap))]))),("ipa",Assigned _ (EmptyLabelMap))])))])))])
Static (fromList [("com",Unassigned (Static (fromList [("someapp",Unassigned (Static (fromList [("api",Unassigned (Static (fromList [("bla",Assigned _ (EmptyLabelMap))])))])))])))])
    modified subdmonains FAILED [1]
```

**Comment by tolysz** [comment]
The logic is fine just the tests are not :)
the last should not be equal as the should be exactly what is printed

**Comment by tolysz** [comment]
I pulled it to the feature branch, and corrected the case. I was not expecting that it is so easy to write tests.

**Comment by creichert** [comment]
Ah cool, we can at least use this setup to explore further testing.

**Pull request closed without merging**
